cloud/urls.py
from django.conf.urls import url
from . import views

app_name = 'cloud'
urlpatterns = [
    # post
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<post_id>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<post_id>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<post_id>[0-9]+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^post/(?P<post_id>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<comment_id>[0-9]+)/delete/$', views.comment_delete, name='comment_delete'),

    # folder
    url(r'^folder/new/(?P<path>.*)$', views.folder_new, name='folder_new'),
    url(r'^folder/delete/(?P<folder_id>[0-9]+)/$', views.folder_delete, name='folder_delete'),

    # file
    url(r'^file/list/(?P<path>.*)$', views.file_list, name='file_list'),
    url(r'^file/upload/(?P<path>.*)$', views.file_upload, name='file_upload'),
    url(r'^file/download/(?P<file_id>[0-9]+)/$', views.file_download, name='file_download'),
    url(r'^file/delete/(?P<file_id>[0-9]+)/$', views.file_delete, name='file_delete'),

    # music
    url(r'^music/$', views.music_list, name='music_list'),
    url(r'^music/(?P<file_id>[0-9]+)/$', views.music_detail, name='music_detail'),

    # json-only
    url(r'^post/find-by-index/(?P<post_index>[0-9]+)/$', views.post_find_by_index, name='post_find_by_index'),
    url(r'^post/recent/$', views.post_recent, name='post_recent'),
]

cloud/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
from django.utils import timezone

from django.db import models


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return u'%s' % self.title


class Comment(models.Model):
    post = models.ForeignKey('cloud.Post', related_name='comments')
    author = models.ForeignKey('auth.User')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return u'%s' % self.text


def user_file_path(instance, filename):
    return os.path.join('NightSky', instance.author.username, instance.path())


class UserFile(models.Model):
    parent = models.ForeignKey('cloud.UserFile', related_name='children', null=True)
    author = models.ForeignKey('auth.User')
    user_file = models.FileField(upload_to=user_file_path, null=True)
    user_folder = models.TextField(null=True)
    uploaded_at = models.DateTimeField(default=timezone.now)
    type = models.CharField(max_length=20, default='etc')

    def name(self):
        if self.user_folder is not None:
            return self.user_folder+os.path.sep
        return os.path.basename(self.user_file.name)

    def path(self):
        if self.parent is None:
            return ''
        return self.parent.path()+self.name()

    def path_recurr(self, arr):
        if self.parent is None:
            return arr
        for i in range(len(arr)):
            arr[i] = ' '+arr[i]
        arr.insert(0, self.name())
        print('\n'.join(arr))
        print()
        return self.parent.path_recurr(arr)

    def path_stair(self):
        return '\n'.join(self.path_recurr([]))

    def __unicode__(self):
        return u'%s' % (self.path())


class MusicFile(UserFile):
    title = models.TextField(default='')
    artist = models.TextField(default='')
    album = models.TextField(default='')
    length_secs = models.IntegerField(default=-1)

    def __unicode__(self):
        return u'%s-%s' % (self.title, self.artist)

cloud/forms.py
from django import forms
from .models import Post, Comment, UserFile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class UserFileForm(forms.ModelForm):
    user_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = UserFile
        fields = ('user_file',)


class UserFolderForm(forms.ModelForm):
    class Meta:
        model = UserFile
        fields = ('user_folder',)

cloud/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import mimetypes
import os
import urllib
from wsgiref.util import FileWrapper

import eyed3
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from cloud.forms import PostForm, CommentForm, UserFileForm, UserFolderForm
from cloud.models import Post, Comment, UserFile, MusicFile


@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    if 'JSON' in request.GET:
        data = []
        for post in posts:
            data.append(dict(
                id=post.pk,
                author=str(post.author),
                title=post.title,
                datetime=str(post.published_date),
                text=post.text,
                comment_count=post.comments.count(),
            ))
        return JsonResponse(data, safe=False)
    else:
        return render(request, 'cloud/post_list.html', {'posts': posts})


@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if 'JSON' in request.GET:
        data = dict(
            title=post.title,
            author=str(post.author),
        )
        return JsonResponse(data, safe=False)
    else:
        return render(request, 'cloud/post_detail.html', {'post': post})


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('cloud:post_detail', post_id=post.pk)
    else:
        form = PostForm()
    return render(request, 'cloud/post_edit.html', {'form': form, 'mode': 'New Post'})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('cloud:post_detail', post_id=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'cloud/post_edit.html', {'form': form, 'mode': 'Edit Post'})


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id, author=request.user)
    post.delete()
    return redirect('cloud:post_list')


@login_required
def add_comment_to_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('cloud:post_detail', post_id=post.pk)
    else:
        form = CommentForm()
    return render(request, 'cloud/add_comment_to_post.html', {'form': form})


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('cloud:post_detail', post_id=comment.post.pk)


def get_folder_or_404(path, user=None, user_folder=None):
    arr = path.split(os.path.sep)
    if user_folder is None:
        user_folder = UserFile.objects.filter(author=user, parent=None)
        if len(user_folder) == 0:
            user_folder = UserFile.objects.create(author=user, user_folder='')
        elif len(user_folder) == 1:
            user_folder = user_folder[0]
        else:
            raise Http404()
    if len(arr) == 1 and arr[0] == '':
        return user_folder
    for child in user_folder.children.all():
        if child.name() == arr[0]+os.path.sep:
            return get_folder_or_404(user_folder=child, path=os.path.join(*(arr[1:])))
    raise Http404()


@login_required
def folder_new(request, path):
    parent = get_folder_or_404(user=request.user, path=path)
    if request.method == 'POST':
        form = UserFolderForm(request.POST)
        if form.is_valid():
            user_folder = form.save(commit=False)
            user_folder.author = request.user
            user_folder.parent = parent
            user_folder.save()
            directory = os.path.dirname(os.path.join(settings.MEDIA_ROOT, 'NightSky', user_folder.author.username, user_folder.path()))
            if not os.path.exists(directory):
                os.makedirs(directory)
            return redirect('cloud:file_list', path=parent.path())
    else:
        form = UserFolderForm()
    return render(request, 'cloud/folder_new.html', {'form': form})


@login_required
def folder_delete(request, folder_id, recc=None):
    user_folder = get_object_or_404(UserFile, pk=folder_id, author=request.user)
    for child in user_folder.children.all():
        if child.user_folder is None:
            file_delete(request, child.id, recc=True)
        else:
            folder_delete(request, child.id, recc=True)
    if user_folder.parent is not None:
        path = user_folder.parent.path()
        os.rmdir(os.path.join(settings.MEDIA_ROOT, 'NightSky', user_folder.author.username, user_folder.path()))
        user_folder.delete()
    else:
        path = ''
    if recc is None:
        return redirect('cloud:file_list', path=path)


@login_required
def file_list(request, path):
    parent = get_folder_or_404(user=request.user, path=path)
    user_files = UserFile.objects.filter(author=request.user, parent=parent).order_by('-uploaded_at')\
        .order_by('-user_folder')
    if 'JSON' in request.GET:
        data = []
        for user_file in user_files:
            data.append(dict(
                id=user_file.pk,
                name=os.path.basename(user_file.user_file.name),
                datetime=str(user_file.uploaded_at),
                type=user_file.type,
            ))
        return JsonResponse(data, safe=False)
    else:
        return render(request, 'cloud/file_list.html', {'user_files': user_files, 'parent': parent})


def user_to_music(user_file):
    music_file = MusicFile()
    music_file.pk = user_file.pk
    music_file.author = user_file.author
    music_file.user_file = user_file.user_file
    music_file.parent = user_file.parent
    music_file.type = 'audio'
    return music_file


@login_required
def file_upload(request, path):
    parent = get_folder_or_404(user=request.user, path=path)
    if request.method == 'POST':
        form = UserFileForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('user_file')
            for file in files:
                user_file = UserFile(user_file=file, parent=parent, author=request.user)
                user_file.save()
                if user_file.user_file.name.split('.')[-1] == 'mp3':
                    music_file = user_to_music(user_file)
                    audio_file = eyed3.load(os.path.join(settings.MEDIA_ROOT, music_file.user_file.name))
                    if audio_file is not None:
                        if audio_file.tag.title is not None:
                            music_file.title = audio_file.tag.title
                        if audio_file.tag.artist is not None:
                            music_file.artist = audio_file.tag.artist
                        if audio_file.tag.album is not None:
                            music_file.album = audio_file.tag.album
                        if audio_file.info.time_secs is not None:
                            music_file.length_secs = audio_file.info.time_secs
                    else:
                        music_file.title = music_file.name().split('.')[0]
                    music_file.save()
                else:
                    user_file.save()
            return redirect('cloud:file_list', path=parent.path())
    else:
        form = UserFileForm()
    return render(request, 'cloud/file_upload.html', {'form': form})


@login_required
def file_download(request, file_id):
    user_file = get_object_or_404(UserFile, pk=file_id, author=request.user)
    file_name = os.path.basename(user_file.user_file.name)
    file_path = os.path.join(settings.MEDIA_ROOT, user_file.user_file.name)
    file_wrapper = FileWrapper(file(file_path, 'rb'))
    file_mimetype = mimetypes.guess_type(file_path)
    response = HttpResponse(file_wrapper, content_type=file_mimetype)
    response['X-Sendfile'] = file_path
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s' % urllib.quote(file_name.encode('utf-8'))
    return response


@login_required
def file_delete(request, file_id, recc=None):
    user_file = get_object_or_404(UserFile, pk=file_id, author=request.user)
    path = user_file.parent.path()
    os.remove(os.path.join(settings.MEDIA_ROOT, user_file.user_file.name))
    user_file.delete()
    if recc is None:
        return redirect('cloud:file_list', path=path)


@login_required
def music_list(request):
    musics = MusicFile.objects.filter(author=request.user).order_by('-uploaded_at')
    if 'JSON' in request.GET:
        data = []
        for music in musics:
            data.append(dict(
                id=music.pk,
                title=music.title,
                artist=music.artist,
                album=music.album,
                path=music.user_file.name,
            ))
        return JsonResponse(data, safe=False)
    else:
        return HttpResponseNotFound()


@login_required
def music_detail(request, file_id):
    music = get_object_or_404(MusicFile, pk=file_id, author=request.user)
    if 'JSON' in request.GET:
        data = dict(
            title=music.title,

templates/cloud/add_comment_to_post.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="add_comment_to_post">
{% endblock %}

{% block content %}
	<h1>New comment</h1>
	<form method="POST" class="post-form">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Send</button>
	</form>
{% endblock %}

templates/cloud/base.html
{% load staticfiles %}

<html>
	<head>
		<title>NightSky</title>
		{% block metadata %}
		{% endblock %}
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<meta name="theme-color" content="#264584">
		
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'style/style.css' %}">
	
		<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
	</head>

	<body>
		<div class="page-header">
			{% if user.is_authenticated %}
				<a href="{% url 'cloud:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
				<p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
			{% else %}
				<a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
			{% endif %}
			<h1><a href="{% url 'cloud:post_list' %}">NightSky</a></h1>
		</div>

		<div class="content container">
			<div class="row">
				<div class="col-md-8">
				{% block content %}
				{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

templates/cloud/file_list.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="file_list">
{% endblock %}

{% block content %}
    <h6>
        <pre>{{ parent.path_stair|linebreaksbr }}</pre>
    </h6>
    {% if parent.parent %}
        <h5><a href="{% url 'cloud:file_list' path=parent.parent.path %}">Back to Parent Folder</a></h5>
    {% endif %}
	<h3><a href="{% url 'cloud:file_upload' path=parent.path %}">Upload File</a></h3>
    <h3><a href="{% url 'cloud:folder_new' path=parent.path %}">Create Folder</a></h3>
	<br>
	{% for file in user_files %}
        {% if file.user_folder %}
        <div class="folder">
            <p><a href="{% url 'cloud:file_list' path=file.path %}">Explore Folder</a></p>
            <p>Name: {{ file.name|linebreaksbr }}</p>
            <p>Uploaded datetime: {{ file.uploaded_at }}</p>
            <a href="{% url 'cloud:folder_delete' folder_id=file.pk %}" onclick="return confirm('Do you want to delete this folder and files?');">Delete Folder and Files</a>
        </div>
        {% else %}
        <div class="file">
            <p><a href="{% url 'cloud:file_download' file_id=file.pk %}">Download File</a></p>
            <p>Name: {{ file.name|linebreaksbr }}</p>
            <p>Type: {{ file.type }}</p>
            <p>Uploaded datetime: {{ file.uploaded_at }}</p>
            <a href="{%  url 'cloud:file_delete' file_id=file.pk %}" onclick="return confirm('Do you want to delete this file?');">Delete File</a>
        </div>
        {% endif %}
	{% endfor %}
{% endblock %}

templates/cloud/file_upload.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="file_upload">
{% endblock %}

{% block content %}
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Upload</button>
	</form>
{% endblock %}

templates/cloud/folder_new.html
{% extends 'cloud/base.html' %}

{% block metadata %}
    <meta name="view_name" content="folder_create">
{% endblock %}

{% block content %}
    <h1>Create New Folder</h1>
    <form method="post" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Create</button>
    </form>
{% endblock %}

templates/cloud/post_detail.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="post_detail">
{% endblock %}

{% block content %}
	<div class="post">
		{% if user.is_authenticated %}
			<a class="btn btn-default" style="float: right" href="{% url 'cloud:post_edit' post_id=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a class="btn btn-default" style="float: right" href="{% url 'cloud:post_delete' post_id=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
		{% endif %}
		{% if post.published_date %}
			<div class="date">
				{{ post.published_date }}
			</div>
		{% endif %}
		<h1>{{ post.title }}</h1>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>

	<hr>
	<a class="btn btn-default" href="{% url 'cloud:add_comment_to_post' post_id=post.pk %}">Add comment</a>
	{% for comment in post.comments.all %}
		<div class="comment">
			<div class="date">
				{{ comment.created_date }}
				<a class="btn btn-default" href="{% url 'cloud:comment_delete' comment_id=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
			</div>
			<strong>{{ comment.author }}</strong>
			<p>{{ comment.text }}</p>
		</div>
	{% empty %}
		<p>No comments here yet</p>
	{% endfor %}

{% endblock %}

templates/cloud/post_edit.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="post_edit">
{% endblock %}

{% block content %}
	<h1>{{ mode }}</h1>
	<form method="POST" class="post-form">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock %}

templates/cloud/post_list.html
{% extends 'cloud/base.html' %}

{% block metadata %}
	<meta name="view_name" content="post_list">
{% endblock %}

{% block content %}
	<h2 name="count">Count: {{ posts.count }}</h2>
	{% for post in posts %}
		<div class="post">
			<div class="date">
				<p>{{ post.published_date }}</p>
			</div>
			<h1><a href="{% url 'cloud:post_detail' post_id=post.pk %}">{{ post.title }}</a></h1>
			<p>{{ post.text|linebreaksbr }}</p>
			Comments: {{ post.comments.count }}
		</div>
	{% endfor %}
{% endblock %}